CustomerModels = {

-- NOT ALL NPC MODELS CAN SPAWN, SO YOU NEED TO TEST THEM BEFORE ADDING THEM TO YOUR WORLD!!!
-- WAOMEN
'hc_hacker',
'a_f_y_beach_01',
'a_f_m_fatbla_01',
'a_f_m_tourist_01',
'a_f_o_genstreet_01',
'a_f_y_eastsa_03',
'a_f_y_eastsa_01',
'a_f_y_hippie_01',
'a_f_y_juggalo_01',
'a_f_y_rurmeth_01',
'cs_janet',
'cs_mrsphillips',
'csb_maude',
'g_f_y_lost_01',
'mp_f_chbar_01',
'mp_f_forgery_01',
'ig_ashley',
'ig_mrs_thornhill',
'ig_tracydisanto',
'u_f_y_taylor',
-- MAN
'a_m_m_eastsa_01',
'a_m_m_farmer_01',
'a_m_m_genfat_02',
'a_m_m_hillbilly_01',
'a_m_m_hillbilly_02',
'a_m_m_mexcntry_01',
'a_m_m_mexlabor_01',
'a_m_m_rurmeth_01',
'a_m_m_salton_01',
'a_m_m_salton_02',
'a_m_m_salton_03',
'a_m_m_socenlat_01',
'a_m_o_acult_02',
'ig_floyd',
'ig_josef',
'ig_wade',
'player_two',
'ig_tomepsilon',
'ig_omega',
'ig_nervousron'
}