Locales = {
    ['de'] = {
        youNotTaxiDriver ="Dispatcher: Du bist kein Taxifahrer!",
        youNotDuty = "Dispatcher: Du bist nicht im Dienst!",
        youNeedDriverLicense = "Dispatcher: Du brauchst einen PKW Führerschein!",
        vehicleAlreadyOutParking = "Dispatcher: Fahrzeug wird bereits ausgeparkt!",
        youHaveVehicle = "Dispatcher: Du hast bereits ein Fahrzeug!",
        vehicleMovedoutHereCarkeys = "Dispatcher: Fahrzeug wurde ausgeparkt hier die Auto Schlüssel.",
        noSpawnAvailable = "Kein Spawnpunkt frei!",
        youCannotParkVehicle = "Dispatcher: Du kannst das Fahrzeug während eines Auftrags nicht einparken!",
        noVehicleAvailable = "Dispatcher: Kein Fahrzeug vorhanden.",
        vehicleParked = "Dispatcher: Fahrzeug eingeparkt.",
        notaxisAvailableNearby = "Dispatcher: Kein Taxifahrzeug in der Nähe",
        newOrder = "Dispatcher: Neuer Auftrag! Entfernung %sm",
        pressKey = "(Drücke %s)",
        jobAccepted = "Dispatcher: Auftrag angenommen. Steige ins Taxi um die Route zu starten.",
        missedOrder = "Auftrag verpasst (%s/%s)",
        orderAutoCanceled = "Dispatcher: Auftrag wurde automatisch storniert.",
        notMove = "Kunde: Warum fahren wir nicht?",
        customerOutofCar = "Kunde verlässt das Fahrzeug!",
        timeLimitExceeded = "Dispatcher: Auftrag automatisch storniert (Zeit überschritten!)",
        notRightWay = "Kunde: Das ist nicht der richtige Weg!",
        customerJumpsOut = "Kunde springt aus dem Taxi!",
        customerCallingPolice = "Der Kunde ruft die Polizei!",
        customerWhereTaxi = "Kunde: Wo bleibt mein Taxi?",
        customerUsedDifferentTaxi = "Dispatcher: Der Kunde hat ein anderes Taxi genommen!",
        customerStopHere = "Kunde: Sie können hier anhalten",
        customerGiveTips = "Kunde hat dir Trinkgeld gegeben: $%s",
        customerPaidTrip = "Fahrt wurde bezahlt: $%s",
        ridePaymentRejected = "Dispatcher: Fahrt konnte nicht bezahlt werden.",
        passengerGottenOff = "Der Fahrgast ist ausgestiegen!",
        taxiDamaged = "Taxi ist beschädigt! Auftrag beendet.",
        youDied = "Du bist gestorben. Auftrag beendet.",
        customersWaiting = "Dispatcher: Lass uns los legen, die Kunden warten!",
        seeYouSoon = "Dispatcher: Bis bald, schönen Tag!",
        welcomeToTaxicompany = "Dispatcher: Willkommen im Taxi-Unternehmen!",
        youQuitJob = "Dispatcher: Du hast als Taxifahrer gekündigt.",
        automaticallyOffDuty = "Dispatcher: Du wurdest automatisch aus dem Dienst genommen!",
        rating = "Bewertung: %s%%",
        badRating = "Dispatcher: Deine Bewertung ist sehr schlecht!",
        firedBadRating = "Dispatcher: Schlechte Taxifahrer haben bei uns nichts verloren.",
        leaveVehicleNow = "Dispatcher: Verlasse das Fahrzeug sofort.",
        vehicleCollected = "Dispatcher: Das Auto wurde von unseren Service Mitarbeitern abgeholt.",
        cleanRideBonus = "Dispatcher: 5 saubere Fahrten in Folge! Bonus: +%s Punkte.",
        rehiredAfterRestart = "Dispatcher: Du kannst erst nach einem Server Neustart wieder eingestellt werden.",
        driveTo = "Kunde: Fahr mich zum %s",
        -- MENU
        headerText ="Taxi Dispatcher",
        singUpJob = "📝 Als Taxifahrer bewerben",
        singUpJpbText = "Starte deine Karriere als Taxifahrer",
        dutyStatusOff = "🔴 Außendienst",
        dutyStatusOn = "🟢 Im Dienst",
        dutyStatusIs = "Dienststatus:",
        vehParkingOut = "🚕 Fahrzeug ausparken",
        vehParkingIn = "📦 Fahrzeug einparken",
        quitJob = "❌ Job kündigen",
        -- HTML TRANSLATE
        taxiTitle = "TAXAMETER",
        fare =      "FAHRT",
        distance =  "DISTANZ",
        time =      "ZEIT",
        today =     "HEUTE",
        rides =     "FAHRTEN",
        rating =    "BEWERTUNG"
    },

    ['en'] = {
        youNotTaxiDriver = "Dispatcher: You're not a Taxidriver!",
        youNotDuty = "Dispatcher: You're not on Duty!",
        youNeedDriverLicense = "Dispatcher: You need a Driver's License!",
        vehicleAlreadyOutParking = "Dispatcher: Vehicle is already being moved out of the Parking space!",
        youHaveVehicle = "Dispatcher: You already have a Vehicle",
        vehicleMovedoutHereCarkeys = "Dispatcher: The Vehicle has been moved out of the Parking Spot. Here are the Car Keys.",
        noSpawnAvailable = "No Spawn Points available!",
        youCannotParkVehicle = "Dispatcher: You cannot park the Vehicle during a Trip!",
        noVehicleAvailable = "Dispatcher: No Vehicle available.",
        vehicleParked = "Dispatcher: Vehicle parked.",
        notaxisAvailableNearby = "Dispatcher: No Taxis available nearby",
        newOrder = "Dispatcher: New order! Distance: %sm",
        pressKey = "(Press %s)",
        jobAccepted = "Dispatcher: Job Accepted. Get in the Taxi to start the Route.",
        missedOrder = "Missed the Order (%s/%s)",
        orderAutoCanceled = "Dispatcher: Order was automatically canceled.",
        notMove = "Customer: Why aren't we leaving?",
        customerOutofCar = "The Customer is getting out of the Car!",
        timeLimitExceeded = "Dispatcher: Order automatically canceled (Timelimit exceeded!)",
        notRightWay = "Customer: This is not the right Way!",
        customerJumpsOut = "A Customer jumps out of the Taxi!",
        customerCallingPolice = "Customer calls the Police!",
        customerWhereTaxi = "Customer: Where's my Taxi?",
        customerUsedDifferentTaxi = "Dispatcher: The Customer took a different Taxi!",
        customerStopHere = "Customer: You can stop here.",
        customerGiveTips = "The customer gave you a Tip: $%s",
        customerPaidTrip = "The Trip has been paid for: $%s",
        ridePaymentRejected = "Dispatcher: Ride payment was rejected.",
        passengerGottenOff = "The Passenger has gotten off!",
        taxiDamaged = "The Taxi is damaged! Job completed.",
        youDied = "You died. Mission complete.",
        customersWaiting = "Dispatcher: Let's get started the Customers are waiting!",
        seeYouSoon = "Dispatcher: See you soon, have a nice Day!",
        welcomeToTaxicompany = "Dispatcher: Welcome to the Taxi-Company!",
        youQuitJob = "Dispatcher: You quit your Job as a Taxidriver",
        automaticallyOffDuty = "Dispatcher: You've been automatically taken off Duty!",
        rating = "Rating: %s%%",
        badRating = "Dispatcher: Your rating is very low!",
        firedBadRating = "Dispatcher: Bad taxi drivers have no place with us.",
        leaveVehicleNow = "Dispatcher: Leave the vehicle immediately.",
        vehicleCollected = "Dispatcher: The vehicle was collected by our service staff.",
        cleanRideBonus = "Dispatcher: 5 clean rides in a row! Bonus: +%s points.",
        rehiredAfterRestart = "Dispatcher: You can only be hired again after a server restart.",
        driveTo = "Customer: Take me to %s",
        -- MENU
        headerText ="Taxi Dispatcher",
        singUpJob = "📝 Apply as a Taxidriver Job",
        singUpJpbText = "Start your career as a Taxidriver",
        dutyStatusOff = "🔴 Off Duty",
        dutyStatusOn = "🟢 On Duty",
        dutyStatusIs = "Duty Status:",
        vehParkingOut = "🚕 Take Vehicle out",
        vehParkingIn = "📦 Parking Vehicle",
        quitJob = "❌ Quit job",
        -- HTML TRANSLATE
        taxiTitle = "TAXAMETER",
        fare = "FARE",
        distance = "DIST.",
        time = "TIME",
        today = "TODAY",
        rides = "RIDES",
        rating = "RATING"
    },

    ['ru'] = {
        youNotTaxiDriver = "Диспетчер: Ты же не таксист!",
        youNotDuty = "Диспетчер: Ты не на дежурстве!",
        youNeedDriverLicense = "Диспетчер: Тебе нужны водительские права!",
        vehicleAlreadyOutParking = "Диспетчер: автомобиль уже разгружается!",
        youHaveVehicle = "Диспетчер: У тебя уже есть автомобиль",
        vehicleMovedoutHereCarkeys = "Диспетчер: Автомобиль припаркован, вот ключи от авто.",
        noSpawnAvailable = "Нет свободных точек появления!",
        youCannotParkVehicle = "Диспетчер: Ты не можешь припарковать автомобиль во время выполнения заказа",
        noVehicleAvailable = "Диспетчер: Транспортное средство отсутствует.",
        vehicleParked = "Диспетчер: автомобиль припаркован.",
        notaxisAvailableNearby = "Диспетчер: нет такси поблизости",
        newOrder = "Диспетчер: Новый заказ! Расстояние: %sm",
        pressKey = "(Hажми %s)",
        jobAccepted = "Диспетчер: Заказ принят. Садитесь в такси, чтобы начать маршрут.",
        missedOrder = "Диспетчер: Ты пропустил свой заказ (%s/%s)",
        orderAutoCanceled = "Диспетчер: Заказ был автоматически аннулирован.",
        notMove = "Клиент: Почему мы не едем?",
        customerOutofCar = "Пассажир выходит из автомобиля!",
        timeLimitExceeded = "Диспетчер: Заказ автоматически аннулирован (время истекло!)",
        notRightWay = "Клиент: Это не тот путь!",
        customerJumpsOut = "Клиент выпрыгивает из такси!",
        customerCallingPolice = "Клиент вызывает полицию!",
        customerWhereTaxi = "Клиент: Где же моё такси?",
        customerUsedDifferentTaxi = "Диспетчер: Клиент сел в другое такси!",
        customerStopHere = "Клиент: Вы можете здесь остановиться.",
        customerGiveTips = "Клиент оставил тебе чаевые: $%s",
        customerPaidTrip = "Поездка оплачена: $%s",
        ridePaymentRejected = "Диспетчер: Оплата поездки была отклонена.",
        passengerGottenOff = "Пассажир вышел!",
        taxiDamaged = "Такси сломано! Заказ отменён.",
        youDied = "Ты умер. Миссия завершена.",
        customersWaiting = "Диспетчер: Давайте начнем, клиенты ждут!",
        seeYouSoon = "Диспетчер: До скорой встречи, хорошего дня!",
        welcomeToTaxicompany = "Диспетчер: Добро пожаловать в таксопарк!",
        youQuitJob = "Диспетчер: Ты уволился с работы таксиста",
        automaticallyOffDuty = "Диспетчер: Тебя автоматически сняли с дежурства!",
        ratingNotify = "Рейтинг: %s%%",
        badRating = "Диспетчер: У тебя очень низкий рейтинг!",
        firedBadRating = "Диспетчер: Плохим таксистам у нас не место.",
        leaveVehicleNow = "Диспетчер: Немедленно покинь автомобиль.",
        vehicleCollected = "Диспетчер: Машину забрали наши сервисные сотрудники.",
        cleanRideBonus = "Диспетчер: 5 чистых поездок подряд! Бонус: +%s очков.",
        rehiredAfterRestart = "Диспетчер: Ты сможешь устроиться снова только после перезапуска сервера.",
        driveTo = "Клиент: Отвези меня в %s",
        -- MENU
        headerText ="Диспетчер такси",
        singUpJob = "📝 Подать заявку на работу таксистом",
        singUpJpbText = "Начни свою карьеру таксиста",
        dutyStatusOff = "🔴 Не на смене",
        dutyStatusOn = "🟢 На смене",
        dutyStatusIs = "Статус смены:",
        vehParkingOut = "🚕 Вывести автомобиль",
        vehParkingIn = "📦 Припарковать автомобиль",
        quitJob = "❌ Уволиться",
        -- HTML TRANSLATE
        taxiTitle = "ТАКСОМЕТР",
        fare =      "ПЛАТА",
        distance =  "ДИСТ.",
        time =      "ВРЕМЯ",
        today =     "СЕГОДНЯ",
        rides =     "ПОЕЗДКИ",
        rating =    "ОЦЕНКА"
    }
}

-- Utility Funktion
CurrentLang = Config.Locale or 'de'
function _U(key, ...)
    if Locales[CurrentLang] and Locales[CurrentLang][key] then
        return string.format(Locales[CurrentLang][key], ...)
    else
        return key
    end
end
